### ISSUE TITLE
Config Example

### ISSUE THREAD

**Issue by jsholiday** [machina86/homebridge-sunsa#1]
Hello! 

Do you have an example of what the config should look like?

**Comment by machina86** [comment]
Here is an example for manually adding an entry into the homebridge config.json. I'll add the example to the readme.md and push it with a couple little house cleaning items in a patch version soon.

```
"platforms": [
	{
		"apiKey": "Your API Key",
		"idUser": 0,
		"platform": "Sunsa"
	}
]
```

**Comment by jsholiday** [comment]
Thanks! The plug-in didn't properly install the first few attempts leaving an empty bridge w/no active plug-in. 
I now see the apikey and idUser fields are built into the setting so no need for manual entry. 

Thank you developing this. My Sunsa Wands just got 10x better!
