### ISSUE TITLE
Create Homekit temperature sensor accessories for each e-wand

### ISSUE THREAD

**Issue by RMCob** [machina86/homebridge-sunsa#6]
**Is your feature request related to a problem? Please describe:**

@machina86 Do you have any plans to expose the wand's temperature sensor values?

**Describe the solution you'd like:**

Create temperature sensor accessories in the plugin for each wand

**Describe alternatives you've considered:**

**Additional context:**

@machina86 I would be willing to do a PR to add the required logic if you will take it and merge into the master branch.

**Comment by machina86** [comment]
I worked on this this weekend and am currently just making sure that it works before pushing it out. Will probably push it out on Monday or Tuesday.

**Comment by RMCob** [comment]
Thanks!
