### ISSUE TITLE
Only 1 blind showing

### ISSUE THREAD

**Issue by cwintr** [machina86/homebridge-sunsa#8]
I downloaded the app and have 8 blinds and added them all to homekit fine, and then now only 1 blind appears and I don't see the remaining 7. I get this log error:

11/8/2023, 9:38:49 AMSunsa BridgeLoaded plugin 'homebridge-sunsa'
11/8/2023, 9:38:49 AMSunsa BridgeLoading 1 platforms...
11/8/2023, 9:38:50 AMSunsa BridgeBridge is running on port 51846.
11/8/2023, 9:38:50 AMSunsa BridgeSunsaFound Device: Bedroom
11/8/2023, 9:38:50 AMSunsa BridgeSunsaAdding new accessory: Bedroom
11/8/2023, 9:38:50 AMSunsa BridgeWARNINGunhandled rejection: Error: UNKNOWN: unknown error, open '/var/lib/hoobs/sunsabridge.accessories/cachedAccessories'

I have Sunsa version 1.1.1 
Hoobs version 4.3.0
Node: 16.20.2
Homebridge: 1.6.0
Using the MacOS App

**Comment by machina86** [comment]
Unfortunately I am not familiar with HOOBS. But according to the error message it looks like it is having a hoobs specific problem retrieving the cached accessories. I would personally remove the sunsa devices that are not showing up from the cache and see if that resolves the issue. You can check here to see how to remove individual cached accessories [https://support.hoobs.org/docs/60e0c685646faaa152f10dd8](https://support.hoobs.org/docs/60e0c685646faaa152f10dd8).
